### ISSUE TITLE
Description in Git

### ISSUE THREAD

**Issue by farkhodkh** [amrkhaledccd/One-to-One-WebSockets-Chat#26]
Hello Friend

Could you please add the description of the demo in git repository?

Thanks

**Comment by amrkhaledccd** [comment]
What do you mean by description of the demo? 

I wrote a Medium story explaing how to build a One-to-One chat

https://medium.com/javarevisited/building-persistable-one-to-one-chat-application-using-spring-boot-and-websockets-303ba5d30bb0

**Comment by farkhodkh** [comment]
Hello friend

Sure, medium is a good one. But it is available only by subscription

**Comment by amrkhaledccd** [comment]
I'm sorry, i can't help with that
